import type { ExaSoundModule } from '../types.js';
export declare function makeCoreSceneBindings(mod: ExaSoundModule): {
    exaGetVersion: import("./binding-utils.js").JsFn<void, [maj: number, min: number, rev: number]>;
    exaGetPathTypeCount: import("./binding-utils.js").JsFn<number, []>;
    exaGetLastError: import("./binding-utils.js").JsFn<string, []>;
    exaGetRuntimeOption: import("./binding-utils.js").JsFn<boolean, [outPtr: number]>;
    exaSetRuntimeOption: import("./binding-utils.js").JsFn<boolean, [optionPtr: number]>;
    exaGetDefaultMeshBuildOption: import("./binding-utils.js").JsFn<boolean, [outPtr: number]>;
    exaSetDefaultMeshBuildOption: import("./binding-utils.js").JsFn<boolean, [optionPtr: number]>;
    exaPropagatorGetGuidePlaneCount: import("./binding-utils.js").JsFn<number, [sceneID: number]>;
    exaPropagatorGetGuidePlanes: import("./binding-utils.js").JsFn<boolean, [sceneID: number, outPtr: number, maxCount: number]>;
    exaPropagatorGetAmbientSoundPathCount: import("./binding-utils.js").JsFn<number, [sceneID: number]>;
    exaPropagatorGetAmbientSoundPaths: import("./binding-utils.js").JsFn<boolean, [sceneID: number, outPtr: number, maxCount: number]>;
    exaPropagatorGetMirrorPositionCount: import("./binding-utils.js").JsFn<number, [sceneID: number]>;
    exaPropagatorGetMirrorPositions: import("./binding-utils.js").JsFn<boolean, [sceneID: number, outPtr: number, maxCount: number]>;
    exaPropagatorGetProfile: import("./binding-utils.js").JsFn<boolean, [outPtr: number]>;
    exaUpdatePropagation: import("./binding-utils.js").JsFn<number, [sceneID: number]>;
    exaPropagatorSetJobTimingOption: import("./binding-utils.js").JsFn<boolean, [optionPtr: number]>;
    exaPropagatorGetJobTimingFrames: import("./binding-utils.js").JsFn<number, [sceneID: number, outPtr: number, maxFrames: number]>;
    exaPropagatorResetJobTiming: import("./binding-utils.js").JsFn<boolean, []>;
    exaPropagatorGetEffectiveMaxDepth: import("./binding-utils.js").JsFn<number, []>;
    exaPropagatorGetSourceEffectiveMaxDepth: import("./binding-utils.js").JsFn<number, [sourceID: number]>;
    exaNewScene: import("./binding-utils.js").JsFn<number, []>;
    exaDeleteScene: import("./binding-utils.js").JsFn<void, [scId: number]>;
    exaTickScene: import("./binding-utils.js").JsFn<void, [scId: number, dt: number]>;
    exaSceneGetObjectCount: import("./binding-utils.js").JsFn<number, [sceneID: number]>;
    exaSceneAddObject: import("./binding-utils.js").JsFn<boolean, [sceneID: number, objectID: number]>;
    exaSceneRemoveObject: import("./binding-utils.js").JsFn<boolean, [sceneID: number, objectID: number]>;
    exaSceneClearObjects: import("./binding-utils.js").JsFn<boolean, [sceneID: number]>;
    exaSceneGetSourceCount: import("./binding-utils.js").JsFn<boolean, [sceneID: number, outPtr: number]>;
    exaSceneAddSource: import("./binding-utils.js").JsFn<boolean, [sceneID: number, sourceID: number]>;
    exaSceneRemoveSource: import("./binding-utils.js").JsFn<boolean, [sceneID: number, sourceID: number]>;
    exaSceneClearSources: import("./binding-utils.js").JsFn<boolean, [sceneID: number]>;
    exaSceneGetListenerCount: import("./binding-utils.js").JsFn<boolean, [sceneID: number, outPtr: number]>;
    exaSceneAddListener: import("./binding-utils.js").JsFn<boolean, [sceneID: number, listenerID: number]>;
    exaSceneRemoveListener: import("./binding-utils.js").JsFn<boolean, [sceneID: number, listenerID: number]>;
    exaSceneClearListeners: import("./binding-utils.js").JsFn<boolean, [sceneID: number]>;
};
//# sourceMappingURL=bindings-core-scene.d.ts.map