import type { ExaSoundModule } from '../types.js';
export declare function makeBindings(mod: ExaSoundModule): {
    exaRenderSound: import("./binding-utils.js").JsFn<boolean, [listenerID: number, soundSourceID: number, inPtr: number, inputLength: number, frameCount: number, channelCount: number, outPtr: number, outputLength: number]>;
    exaSetMaxDelay: import("./binding-utils.js").JsFn<boolean, [lid: number, sid: number, v: number]>;
    exaSetPathFadeTime: import("./binding-utils.js").JsFn<boolean, [lid: number, sid: number, v: number]>;
    exaSetMaxDelayRate: import("./binding-utils.js").JsFn<boolean, [lid: number, sid: number, v: number]>;
    exaGetMaxDelayRate: import("./binding-utils.js").JsFn<boolean, [lid: number, sid: number, outPtr: number]>;
    exaGetStatistics: import("./binding-utils.js").JsFn<boolean, [lid: number, sid: number, outPtr: number, len: number]>;
    exaListenerClearRenderState: import("./binding-utils.js").JsFn<boolean, [lid: number]>;
    exaSetMemoryTraceOption: import("./binding-utils.js").JsFn<boolean, [optPtr: number]>;
    exaMemoryTraceMark: import("./binding-utils.js").JsFn<boolean, [tag: string]>;
    exaGetMemoryTraceSnapshot: import("./binding-utils.js").JsFn<boolean, [outPtr: number]>;
    exaStatistics_GetRayTraversalCount: import("./binding-utils.js").JsFn<number, [type: number]>;
    exaStatistics_GetRayTraversals: import("./binding-utils.js").JsFn<boolean, [type: number, outPtr: number, count: number]>;
    exaStatistics_GetRayHitTriangleCount: import("./binding-utils.js").JsFn<number, [type: number]>;
    exaStatistics_GetRayHitTriangles: import("./binding-utils.js").JsFn<boolean, [type: number, outPtr: number, count: number]>;
    exaGetSortedIRDatas: import("./binding-utils.js").JsFn<boolean, []>;
    exaGetValidPathCount: import("./binding-utils.js").JsFn<number, []>;
    exaGetValidPaths: import("./binding-utils.js").JsFn<number, [outPtr: number, count: number]>;
    exaFindAttenuationForDistance: import("./binding-utils.js").JsFn<number, [sceneID: number, sourceID: number, pathType: number, targetAtten: number]>;
    exaTestRayGeneration: import("./binding-utils.js").JsFn<void, [outPtr: number, w: number, h: number]>;
    exaNewListener: import("./binding-utils.js").JsFn<number, []>;
    exaDeleteListener: import("./binding-utils.js").JsFn<void, [id: number]>;
    exaListenerGetTransform: import("./binding-utils.js").JsFn<boolean, [id: number, outPtr: number]>;
    exaListenerSetTransform: import("./binding-utils.js").JsFn<boolean, [id: number, tPtr: number]>;
    exaListenerGetPosition: import("./binding-utils.js").JsFn<boolean, [id: number, outVec3Ptr: number]>;
    exaListenerSetPosition: import("./binding-utils.js").JsFn<boolean, [id: number, vec3Ptr: number]>;
    exaListenerGetVelocity: import("./binding-utils.js").JsFn<boolean, [id: number, outVec3Ptr: number]>;
    exaListenerSetVelocity: import("./binding-utils.js").JsFn<boolean, [id: number, vec3Ptr: number]>;
    exaListenerSetOrientation: import("./binding-utils.js").JsFn<boolean, [id: number, mat3x3Ptr: number]>;
    exaListenerSetOrientation_Quaternion: import("./binding-utils.js").JsFn<boolean, [id: number, qx: number, qy: number, qz: number, qw: number]>;
    exaListenerGetOption: import("./binding-utils.js").JsFn<boolean, [id: number, outPtr: number]>;
    exaListenerSetOption: import("./binding-utils.js").JsFn<boolean, [id: number, optPtr: number]>;
    exaListenerGetAudioOption: import("./binding-utils.js").JsFn<boolean, [id: number, outPtr: number]>;
    exaListenerSetAudioOption: import("./binding-utils.js").JsFn<boolean, [id: number, optPtr: number]>;
    exaListenerGetAmbientPhysicalFilterOption: import("./binding-utils.js").JsFn<boolean, [id: number, outPtr: number]>;
    exaListenerSetAmbientPhysicalFilterOption: import("./binding-utils.js").JsFn<boolean, [id: number, optPtr: number]>;
    exaListenerGetAirAbsorptionOption: import("./binding-utils.js").JsFn<boolean, [id: number, outPtr: number]>;
    exaListenerSetAirAbsorptionOption: import("./binding-utils.js").JsFn<boolean, [id: number, optPtr: number]>;
    exaListenerSetLateReverbMode: import("./binding-utils.js").JsFn<boolean, [id: number, mode: number]>;
    exaListenerGetLateReverbMode: import("./binding-utils.js").JsFn<boolean, [id: number, outPtr: number]>;
    exaListenerSetPerBandLateReverb: import("./binding-utils.js").JsFn<boolean, [id: number, enabled: boolean]>;
    exaListenerGetPerBandLateReverb: import("./binding-utils.js").JsFn<boolean, [id: number, outPtr: number]>;
    exaListenerSetHrtfMode: import("./binding-utils.js").JsFn<boolean, [id: number, mode: number]>;
    exaListenerGetHrtfMode: import("./binding-utils.js").JsFn<boolean, [id: number, outPtr: number]>;
    exaListenerSetDiffuseEnabled: import("./binding-utils.js").JsFn<boolean, [id: number, enabled: boolean]>;
    exaListenerGetDiffuseEnabled: import("./binding-utils.js").JsFn<boolean, [id: number, outPtr: number]>;
    exaListenerSetDiffuseQuality: import("./binding-utils.js").JsFn<boolean, [id: number, quality: number]>;
    exaListenerGetDiffuseQuality: import("./binding-utils.js").JsFn<boolean, [id: number, outPtr: number]>;
    exaListenerSetHrtfQuality: import("./binding-utils.js").JsFn<boolean, [id: number, quality: number]>;
    exaListenerGetHrtfQuality: import("./binding-utils.js").JsFn<boolean, [id: number, outPtr: number]>;
    exaListenerSetEarlyRenderPathBudget: import("./binding-utils.js").JsFn<boolean, [id: number, budget: number]>;
    exaListenerGetEarlyRenderPathBudget: import("./binding-utils.js").JsFn<boolean, [id: number, outPtr: number]>;
    exaListenerSetDelayInterpolation: import("./binding-utils.js").JsFn<boolean, [id: number, mode: number]>;
    exaListenerGetDelayInterpolation: import("./binding-utils.js").JsFn<boolean, [id: number, outPtr: number]>;
    exaListenerLoadParametricHrtf: import("./binding-utils.js").JsFn<boolean, [id: number, dataPtr: number, length: number]>;
    exaListenerLoadConvolutionHrtf: import("./binding-utils.js").JsFn<boolean, [id: number, dataPtr: number, length: number]>;
    exaPropagatorGetPerceptualDepthOption: import("./binding-utils.js").JsFn<boolean, [outPtr: number]>;
    exaPropagatorSetPerceptualDepthOption: import("./binding-utils.js").JsFn<boolean, [optPtr: number]>;
    exaListenerSetPathEnable: import("./binding-utils.js").JsFn<boolean, [id: number, pathType: number, enabled: boolean]>;
    exaListenerIsPathEnabled: import("./binding-utils.js").JsFn<boolean, [id: number, pathType: number, outPtr: number]>;
    exaListenerSetRayCount: import("./binding-utils.js").JsFn<boolean, [id: number, w: number, h: number]>;
    exaListenerGetRayCount: import("./binding-utils.js").JsFn<boolean, [id: number, wPtr: number, hPtr: number]>;
    exaListenerSetRayDepth: import("./binding-utils.js").JsFn<boolean, [id: number, d: number]>;
    exaListenerGetRayDepth: import("./binding-utils.js").JsFn<boolean, [id: number, outPtr: number]>;
    exa_audio_worklet_init: import("./binding-utils.js").JsFn<void, [ctxHandle: number, onReadyPtr: number, userDataPtr: number]>;
    exa_audio_worklet_create_node: import("./binding-utils.js").JsFn<number, [ctxHandle: number, listenerID: number, sourceID: number, channels: number]>;
    exa_audio_worklet_create_mixer_node: import("./binding-utils.js").JsFn<number, [ctxHandle: number, listenerID: number, sourceIDsPtr: number, sourceCount: number, channels: number]>;
    exaNewObject: import("./binding-utils.js").JsFn<number, []>;
    exaDeleteObject: import("./binding-utils.js").JsFn<void, [objectID: number]>;
    exaObjectSetUpdateType: import("./binding-utils.js").JsFn<boolean, [objectID: number, t: number]>;
    exaObjectgetUpdateType: import("./binding-utils.js").JsFn<number, [objectID: number]>;
    exaObjectGetPosition: import("./binding-utils.js").JsFn<boolean, [id: number, x: number, y: number, z: number]>;
    exaObjectSetPosition: import("./binding-utils.js").JsFn<boolean, [id: number, x: number, y: number, z: number]>;
    exaObjectGetRotation: import("./binding-utils.js").JsFn<boolean, [id: number, qx: number, qy: number, qz: number, qw: number]>;
    exaObjectSetRotation: import("./binding-utils.js").JsFn<boolean, [id: number, qx: number, qy: number, qz: number, qw: number]>;
    exaObjectGetScale: import("./binding-utils.js").JsFn<boolean, [id: number, sx: number, sy: number, sz: number]>;
    exaObjectSetScale: import("./binding-utils.js").JsFn<boolean, [id: number, sx: number, sy: number, sz: number]>;
    exaObjectGetMesh: import("./binding-utils.js").JsFn<boolean, [id: number, outPtr: number]>;
    exaObjectSetMesh: import("./binding-utils.js").JsFn<boolean, [id: number, meshID: number]>;
    exaNewMesh: import("./binding-utils.js").JsFn<number, []>;
    exaDeleteMesh: import("./binding-utils.js").JsFn<void, [mesh: number]>;
    exaMeshSetData: import("./binding-utils.js").JsFn<boolean, [mesh: number, vertsPtr: number, numVerts: number, trisPtr: number, numTris: number, bvhMaxDepth: number, primPerLeaf: number, bvhType: number]>;
    exaGetSoundMesh: import("./binding-utils.js").JsFn<number, [path: string]>;
    exaRegisterMesh: import("./binding-utils.js").JsFn<boolean, [path: string, meshID: number]>;
    exaGetSoundMeshVrtsTrisAll: import("./binding-utils.js").JsFn<boolean, [meshID: number, outPtrPtr: number, outCountPtr: number]>;
    exaMeshUpdateVertices: import("./binding-utils.js").JsFn<boolean, [meshID: number, vertsPtr: number, numVerts: number]>;
    exaMeshRefit: import("./binding-utils.js").JsFn<boolean, [meshID: number]>;
    exaMeshSetMaterial: import("./binding-utils.js").JsFn<boolean, [meshID: number, matIdx: number]>;
    exaMeshSetMaterialRange: import("./binding-utils.js").JsFn<boolean, [meshID: number, triStart: number, triCount: number, matIdx: number]>;
    exaIntersectSoundMesh: import("./binding-utils.js").JsFn<boolean, [sceneID: number, rayPtr: number, hitPtr: number]>;
    exaAddSoundMaterial: import("./binding-utils.js").JsFn<number, [matPtr: number]>;
    exaSetSoundMaterial: import("./binding-utils.js").JsFn<boolean, [index: number, matPtr: number]>;
    exaNewSoundSource: import("./binding-utils.js").JsFn<number, []>;
    exaDeleteSoundSource: import("./binding-utils.js").JsFn<void, [id: number]>;
    exaSoundSourceGetPosition: import("./binding-utils.js").JsFn<boolean, [id: number, xPtr: number, yPtr: number, zPtr: number]>;
    exaSoundSourceSetPosition: import("./binding-utils.js").JsFn<boolean, [id: number, x: number, y: number, z: number]>;
    exaSoundSourceGetDirection: import("./binding-utils.js").JsFn<boolean, [id: number, xPtr: number, yPtr: number, zPtr: number]>;
    exaSoundSourceSetDirection: import("./binding-utils.js").JsFn<boolean, [id: number, x: number, y: number, z: number]>;
    exaSoundSourceGetVelocity: import("./binding-utils.js").JsFn<boolean, [id: number, xPtr: number, yPtr: number, zPtr: number]>;
    exaSoundSourceSetVelocity: import("./binding-utils.js").JsFn<boolean, [id: number, x: number, y: number, z: number]>;
    exaSoundSourceSetIntensity: import("./binding-utils.js").JsFn<boolean, [id: number, v: number]>;
    exaSoundSourceGetIntensity: import("./binding-utils.js").JsFn<boolean, [id: number, outPtr: number]>;
    exaSoundSourceSetGainBoostDb: import("./binding-utils.js").JsFn<boolean, [id: number, db: number]>;
    exaSoundSourceGetGainBoostDb: import("./binding-utils.js").JsFn<boolean, [id: number, outPtr: number]>;
    exaSoundSourceSetReverbSendDb: import("./binding-utils.js").JsFn<boolean, [id: number, db: number]>;
    exaSoundSourceGetReverbSendDb: import("./binding-utils.js").JsFn<boolean, [id: number, outPtr: number]>;
    exaSoundSourceSetReflectionSendDb: import("./binding-utils.js").JsFn<boolean, [id: number, db: number]>;
    exaSoundSourceGetReflectionSendDb: import("./binding-utils.js").JsFn<boolean, [id: number, outPtr: number]>;
    exaSoundSourceSetPathEnable: import("./binding-utils.js").JsFn<boolean, [id: number, pathType: number, enabled: boolean]>;
    exaSoundSourceIsPathEnabled: import("./binding-utils.js").JsFn<boolean, [id: number, pathType: number, outPtr: number]>;
    exaSoundSourceSetAmbientEnabled: import("./binding-utils.js").JsFn<boolean, [id: number, enabled: boolean]>;
    exaSoundSourceGetAmbientEnabled: import("./binding-utils.js").JsFn<boolean, [id: number, outPtr: number]>;
    exaSoundSourceSetDepth: import("./binding-utils.js").JsFn<boolean, [id: number, d: number]>;
    exaSoundSourceGetDepth: import("./binding-utils.js").JsFn<boolean, [id: number, outPtr: number]>;
    exaSoundSourceSetRayCount: import("./binding-utils.js").JsFn<boolean, [id: number, w: number, h: number]>;
    exaSoundSourceGetRayCount: import("./binding-utils.js").JsFn<boolean, [id: number, wPtr: number, hPtr: number]>;
    exaSoundSourceGetDistanceAttenuation: import("./binding-utils.js").JsFn<boolean, [id: number, pathType: number, outVec3Ptr: number]>;
    exaSoundSourceSetDistanceAttenuation: import("./binding-utils.js").JsFn<boolean, [id: number, pathType: number, vec3Ptr: number]>;
    exaSoundSourceGetDistanceAttenuations: import("./binding-utils.js").JsFn<boolean, [id: number, dPtr: number, rPtr: number, dfPtr: number, rvPtr: number]>;
    exaSoundSourceSetDistanceAttenuations: import("./binding-utils.js").JsFn<boolean, [id: number, dPtr: number, rPtr: number, dfPtr: number, rvPtr: number]>;
    exaGetVersion: import("./binding-utils.js").JsFn<void, [maj: number, min: number, rev: number]>;
    exaGetPathTypeCount: import("./binding-utils.js").JsFn<number, []>;
    exaGetLastError: import("./binding-utils.js").JsFn<string, []>;
    exaGetRuntimeOption: import("./binding-utils.js").JsFn<boolean, [outPtr: number]>;
    exaSetRuntimeOption: import("./binding-utils.js").JsFn<boolean, [optionPtr: number]>;
    exaGetDefaultMeshBuildOption: import("./binding-utils.js").JsFn<boolean, [outPtr: number]>;
    exaSetDefaultMeshBuildOption: import("./binding-utils.js").JsFn<boolean, [optionPtr: number]>;
    exaPropagatorGetGuidePlaneCount: import("./binding-utils.js").JsFn<number, [sceneID: number]>;
    exaPropagatorGetGuidePlanes: import("./binding-utils.js").JsFn<boolean, [sceneID: number, outPtr: number, maxCount: number]>;
    exaPropagatorGetAmbientSoundPathCount: import("./binding-utils.js").JsFn<number, [sceneID: number]>;
    exaPropagatorGetAmbientSoundPaths: import("./binding-utils.js").JsFn<boolean, [sceneID: number, outPtr: number, maxCount: number]>;
    exaPropagatorGetMirrorPositionCount: import("./binding-utils.js").JsFn<number, [sceneID: number]>;
    exaPropagatorGetMirrorPositions: import("./binding-utils.js").JsFn<boolean, [sceneID: number, outPtr: number, maxCount: number]>;
    exaPropagatorGetProfile: import("./binding-utils.js").JsFn<boolean, [outPtr: number]>;
    exaUpdatePropagation: import("./binding-utils.js").JsFn<number, [sceneID: number]>;
    exaPropagatorSetJobTimingOption: import("./binding-utils.js").JsFn<boolean, [optionPtr: number]>;
    exaPropagatorGetJobTimingFrames: import("./binding-utils.js").JsFn<number, [sceneID: number, outPtr: number, maxFrames: number]>;
    exaPropagatorResetJobTiming: import("./binding-utils.js").JsFn<boolean, []>;
    exaPropagatorGetEffectiveMaxDepth: import("./binding-utils.js").JsFn<number, []>;
    exaPropagatorGetSourceEffectiveMaxDepth: import("./binding-utils.js").JsFn<number, [sourceID: number]>;
    exaNewScene: import("./binding-utils.js").JsFn<number, []>;
    exaDeleteScene: import("./binding-utils.js").JsFn<void, [scId: number]>;
    exaTickScene: import("./binding-utils.js").JsFn<void, [scId: number, dt: number]>;
    exaSceneGetObjectCount: import("./binding-utils.js").JsFn<number, [sceneID: number]>;
    exaSceneAddObject: import("./binding-utils.js").JsFn<boolean, [sceneID: number, objectID: number]>;
    exaSceneRemoveObject: import("./binding-utils.js").JsFn<boolean, [sceneID: number, objectID: number]>;
    exaSceneClearObjects: import("./binding-utils.js").JsFn<boolean, [sceneID: number]>;
    exaSceneGetSourceCount: import("./binding-utils.js").JsFn<boolean, [sceneID: number, outPtr: number]>;
    exaSceneAddSource: import("./binding-utils.js").JsFn<boolean, [sceneID: number, sourceID: number]>;
    exaSceneRemoveSource: import("./binding-utils.js").JsFn<boolean, [sceneID: number, sourceID: number]>;
    exaSceneClearSources: import("./binding-utils.js").JsFn<boolean, [sceneID: number]>;
    exaSceneGetListenerCount: import("./binding-utils.js").JsFn<boolean, [sceneID: number, outPtr: number]>;
    exaSceneAddListener: import("./binding-utils.js").JsFn<boolean, [sceneID: number, listenerID: number]>;
    exaSceneRemoveListener: import("./binding-utils.js").JsFn<boolean, [sceneID: number, listenerID: number]>;
    exaSceneClearListeners: import("./binding-utils.js").JsFn<boolean, [sceneID: number]>;
    exaInit: () => void;
    exaReset: () => void;
    exaIsInitialized: () => boolean;
    exaEnableGpuPropagation: () => Promise<boolean>;
};
export type Bindings = ReturnType<typeof makeBindings>;
//# sourceMappingURL=bindings.d.ts.map