import { Diagnostics } from './Diagnostics.js';
import { MaterialTable } from './MaterialTable.js';
import { Propagator } from './Propagator.js';
import { SoundListener } from './SoundListener.js';
import { SoundMesh, type MeshBuildOptions } from './SoundMesh.js';
import { SoundObject } from './SoundObject.js';
import { SoundScene } from './SoundScene.js';
import { SoundSource } from './SoundSource.js';
import { SoundCollider, type SoundColliderBuildOptions } from './SoundCollider.js';
import { Mesh, Listener, Source, type CoordinateTransform, type ObjectUpdateType, type QualityTier, type SourcePathOptions, type Vec3In } from './facade.js';
import type { Bindings, Heap, MeshBuildOption, RuntimeOption, STOption } from './native/index.js';
import type { DebugSnapshot, DebugSnapshotOptions, StartupOptions } from './control-protocol.js';
import type { WorkerHostedControlState } from './soundtrace-mt-worker-load.js';
import type { ExaSoundModule, SoundTraceOptions, ThreadMode } from './types.js';
import type { Disposable } from './Disposable.js';
import type { MaterialRef } from './material-resolver.js';
import type { MeshTriangle } from './SoundTrace-public.js';
import { SoundTraceMtFacadeState } from './soundtrace-mt-facade-state.js';
import { SoundTraceMtUnsupportedError, type HrtfLoadMode, type HrtfSource, type StatisticsSnapshot, type StatisticsSnapshotOptions } from './SoundTrace-types.js';
export { SoundTraceMtUnsupportedError } from './SoundTrace-types.js';
export type { HrtfLoadMode, HrtfSource, StatisticsPathSnapshot, StatisticsSnapshot, StatisticsSnapshotOptions, StatisticsSourceSnapshot } from './SoundTrace-types.js';
export declare class SoundTrace implements Disposable {
    readonly ctx: AudioContext;
    readonly thread: ThreadMode;
    readonly coreBaseUrl: string;
    readonly assetBaseUrl: string;
    readonly propagationThreadCount: number | undefined;
    readonly defaultMeshBuild: MeshBuildOptions | undefined;
    readonly coordinateTransform: CoordinateTransform;
    module: ExaSoundModule | null;
    _bindings: Bindings | null;
    _heap: Heap | null;
    _output: GainNode | null;
    _workerHostedControl: WorkerHostedControlState | null;
    _mtFacadeState: SoundTraceMtFacadeState | null;
    _loadPromise: Promise<void> | null;
    _disposed: boolean;
    _materials: MaterialTable | null;
    _propagator: Propagator | null;
    _diagnostics: Diagnostics | null;
    readonly _autoGpu: boolean;
    readonly _autoLoadMaterials: boolean;
    _scene: SoundScene | null;
    _sceneListener: SoundListener | null;
    _facadeListener: Listener | null;
    _aliasReverseIndex: Map<string, string>;
    _nameToIndex: Map<string, number>;
    _defaultMaterialType: number;
    _ctxHandle: number;
    _workletInitPromise: Promise<void> | null;
    _mtAudioWorkletInitPromise: Promise<void> | null;
    _gpuEnablePromise: Promise<boolean> | null;
    _nextMtAudioSessionId: number;
    quality: QualityTier;
    constructor(audioContext: AudioContext, options?: SoundTraceOptions);
    static create(audioContext: AudioContext, options?: SoundTraceOptions): Promise<SoundTrace>;
    load(): Promise<void>;
    loadSingleThreadCore(): Promise<void>;
    loadWorkerHostedControl(): Promise<void>;
    enableGpu(): Promise<boolean>;
    get output(): AudioNode;
    get audioContext(): AudioContext;
    get workerHostedControl(): boolean;
    bindings(): Bindings;
    heap(): Heap;
    assertLocalControlAvailable(operation: string): void;
    createMtUnsupportedError(operation: string): SoundTraceMtUnsupportedError;
    buildWorkerStartupOptions(): StartupOptions;
    resolveWorkerPthreadPoolSize(): number;
    mtFacadeState(): SoundTraceMtFacadeState | null;
    applyStartupOptions(): void;
    applyQualityPreset(listener: SoundListener, preset?: STOption): void;
    getRuntimeOption(): RuntimeOption;
    getDefaultMeshBuildOption(): MeshBuildOption;
    createScene(): SoundScene;
    createObject(): SoundObject;
    createMesh(): SoundMesh;
    createCollider(opts?: SoundColliderBuildOptions): SoundCollider;
    createSource(): SoundSource;
    createListener(): SoundListener;
    loadHrtf(mode: HrtfLoadMode, source?: HrtfSource): Promise<void>;
    readHrtfSource(mode: HrtfLoadMode, source: HrtfSource | undefined): Promise<Uint8Array>;
    hrtfUrl(mode: HrtfLoadMode, source: string | URL | undefined): string;
    fetchHrtfBytes(url: string): Promise<Uint8Array>;
    loadMaterialAssets(): Promise<void>;
    facadeScene(): SoundScene;
    get listener(): Listener;
    setQuality(quality: QualityTier): this;
    setAudioOption(options?: {
        readonly inputSampleCount?: number;
        readonly outputChannels?: number;
    }): this;
    getStatistics(options?: StatisticsSnapshotOptions): StatisticsSnapshot;
    getSourceStatisticsSnapshot(source: Source, length: number): import("./SoundTrace-types.js").StatisticsSourceSnapshot;
    addMesh(opts: {
        vertices: ArrayLike<number>;
        indices?: ArrayLike<number>;
        triangles?: MeshTriangle[];
        material?: MaterialRef;
        updateType?: ObjectUpdateType;
    }): Mesh;
    removeMesh(mesh: Mesh): this;
    addSource(opts: {
        position: Vec3In;
        gain?: number;
        paths?: SourcePathOptions;
    }): Source;
    update(dt?: number): number | Promise<number>;
    debugSnapshot(options?: DebugSnapshotOptions): Promise<DebugSnapshot>;
    get materials(): MaterialTable;
    get propagator(): Propagator;
    get diagnostics(): Diagnostics;
    reset(): void | Promise<void>;
    getPathTypeCount(): number;
    getLastError(): string;
    registerMeshPath(path: string, meshID: number): boolean;
    lookupMeshByPath(path: string): number;
    _playSource(source: Source, channels: number): Promise<AudioWorkletNode>;
    createWorkletNode(listener: SoundListener, source: SoundSource, channels?: number): Promise<AudioWorkletNode>;
    createMtAudioWorkletNode(sourceHandle: number, channels: number): Promise<AudioWorkletNode>;
    pumpMtControlLoop(): void;
    createMixerWorkletNode(listener: SoundListener, sources: readonly SoundSource[], channels?: number): Promise<AudioWorkletNode>;
    audioWorkletNodeFromHandle(handle: number): AudioWorkletNode;
    _ensureWorkletReady(): Promise<void>;
    _bootstrapWorklet(): Promise<void>;
    requireModule(): ExaSoundModule;
    ensureMtAudioWorkletReady(): Promise<void>;
    loadMtAudioWorkletModule(): Promise<void>;
    get disposed(): boolean;
    dispose(): void;
    [Symbol.dispose](): void;
}
//# sourceMappingURL=SoundTrace.d.ts.map